Add price symbol param
getumbrel/umbrel-manager pull request #56
Opened 2020-10-24 19:23 UTC by EddWills95

- Adds a price symbol parameter to the API call
- This will allow other currencies (a setting that could be added to the UI)

2020-10-25 00:39 UTC, louneskmt requested changes
A lot of changes seems like eslint modifications. I think you should only keep 
your "concrete" modification in this PR, without the prettier code 😉

2020-10-25 10:23 UTC, EddWills95 commented
made the changes, removing prettier. Any reason that you the project isn't following the ESLint rules?

2020-10-31 11:16 UTC, mayankchhabra requested changes
Looks great, @EddWills95! Thanks for the PR! Just added a tiny suggestion.

2020-10-31 11:16 UTC, mayankchhabra commented on routes/v1/external.js
> +  const sym = req.params.sym || "USD";
`sym` is nice and short, although we can probably rename it to something that's more verbal, like `currency`:

```suggestion
  const currency = req.params.currency || "USD";
```

2020-10-31 11:16 UTC, mayankchhabra commented on routes/v1/external.js
> +    url: `https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=${sym}`,
^ Same

```suggestion
    url: `https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=${currency}`,
```

2020-10-31 15:23 UTC, mayankchhabra approved these changes
Awesome, thanks again @EddWills95! Congrats on your first, PR! 🎉

2020-10-31 15:24 UTC, merged